[package]
name = "metar-test"
version = "0.8.2"
authors = ["Lily Hopkins <lily@hpkns.uk>"]
edition = "2024"
publish = false

[dependencies]
anyhow = "*"
metar = "*"
regex = "*"
reqwest = { version = "*", features = ["blocking"] }

[profile.release]
lto = true
panic = "abort"
